"use client"

import { CRMNavigation } from "@/components/admin/crm/crm-navigation"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { 
  Table, 
  TableBody, 
  TableCell, 
  TableHead, 
  TableHeader, 
  TableRow 
} from "@/components/ui/table"
import { Button } from "@/components/ui/button"
import { useEffect, useState } from "react"
import { 
  BarChart, 
  Bar, 
  XAxis, 
  YAxis, 
  CartesianGrid, 
  Tooltip, 
  ResponsiveContainer, 
  LineChart, 
  Line 
} from "recharts"
import { getCRMReports } from "@/app/actions/crm-reports"

export default function ReportsPage() {
  const [mounted, setMounted] = useState(false)
  const [data, setData] = useState<any>(null)

  useEffect(() => {
    async function loadData() {
      const result = await getCRMReports()
      setData(result)
      setMounted(true)
    }
    loadData()
  }, [])

  if (!mounted || !data) {
    return <div className="p-6">Loading real-time analytics...</div>
  }

  return (
    <div className="p-6 space-y-6">
      <div>
        <h1 className="text-3xl font-serif font-bold italic">CRM Reports</h1>
        <p className="text-muted-foreground">Analyze customer behavior and loyalty performance.</p>
      </div>

      <CRMNavigation />

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Card>
          <CardHeader>
            <CardTitle>Member Signups vs Redemptions</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="h-[300px] w-full">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={data.graphData}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="name" />
                  <YAxis />
                  <Tooltip />
                  <Bar dataKey="signups" fill="hsl(var(--primary))" name="New Signups" />
                  <Bar dataKey="redemptions" fill="hsl(var(--muted-foreground))" name="Redemptions" />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Activity Trend</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="h-[300px] w-full">
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={data.graphData}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="name" />
                  <YAxis />
                  <Tooltip />
                  <Line type="monotone" dataKey="signups" stroke="hsl(var(--primary))" strokeWidth={2} name="Activity Level" />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Loyalty ROI Summary</CardTitle>
        </CardHeader>
        <CardContent className="p-0">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Metric</TableHead>
                <TableHead>Current Total</TableHead>
                <TableHead>Description</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {[
                { metric: "Loyalty Revenue", value: `KES ${data.loyaltyRevenue.toLocaleString()}`, desc: "Total revenue generated by loyalty program members" },
                { metric: "Avg. Loyalty Transaction", value: `KES ${Math.round(data.avgLoyaltyOrder).toLocaleString()}`, desc: "Average spend per order for loyalty members" },
                { metric: "Total Redemptions", value: data.graphData.reduce((acc: any, curr: any) => acc + curr.redemptions, 0), desc: "Points redemptions processed this week" },
              ].map((item, i) => (
                <TableRow key={i}>
                  <TableCell className="font-medium">{item.metric}</TableCell>
                  <TableCell className="font-black text-primary">{item.value}</TableCell>
                  <TableCell className="text-muted-foreground">{item.desc}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  )
}
